import type { PhotoCollection } from "@/content/types";

export const photoCollections: PhotoCollection[] = [
  {
    title: "UWB IEEE Senior Sendoff 2025",
    slug: "senior-sendoff",
    image: "/images/thumbs/senior-sendoff.jpg",
    date: "2025-06-01",
    featured: true,
    photos: [
      { filename: "senior-sendoff.jpg" },
      { filename: "senior-sendoff-2.jpg" },
      { filename: "senior-sendoff-3.jpg" },
      { filename: "senior-sendoff-4.jpg" },
      { filename: "senior-sendoff-5.jpg" },
      { filename: "senior-sendoff-6.jpg" },
      { filename: "senior-sendoff-7.jpg" },
      { filename: "senior-sendoff-8.jpg" },
      { filename: "senior-sendoff-9.jpg" },
      { filename: "senior-sendoff-10.jpg" },
      { filename: "senior-sendoff-11.jpg" },
      { filename: "senior-sendoff-12.jpg" },
      { filename: "senior-sendoff-13.jpg" },
      { filename: "senior-sendoff-14.jpg" },
      { filename: "senior-sendoff-15.jpg" },
      { filename: "senior-sendoff-16.jpg" },
    ],
  },
  {
    title: "San Diego 2024",
    slug: "san-diego",
    image: "/images/thumbs/san-diego-2.jpg",
    date: "2024-01-01",
    location: "San Diego, CA",
    featured: true,
    photos: [
      { filename: "san-diego.jpg" },
      { filename: "san-diego-2.jpg" },
      { filename: "san-diego-3.jpg" },
      { filename: "san-diego-4.jpg" },
      { filename: "san-diego-5.jpg" },
      { filename: "san-diego-6.jpg" },
      { filename: "san-diego-7.jpg" },
      { filename: "san-diego-8.jpg" },
      { filename: "san-diego-9.jpg" },
      { filename: "san-diego-10.jpg" },
    ],
  },
  {
    title: "Oregon 2024",
    slug: "oregon-2024",
    image: "/images/thumbs/oregon-3.jpg",
    date: "2024-01-01",
    location: "Oregon",
    featured: true,
    photos: [
      { filename: "oregon.jpg" },
      { filename: "oregon-2.jpg" },
      { filename: "oregon-3.jpg" },
    ],
  },
  {
    title: "Chicago 2024",
    slug: "chicago-2024",
    image: "/images/thumbs/chicago.jpg",
    date: "2024-01-01",
    location: "Chicago, IL",
    featured: true,
    photos: [
      { filename: "chicago.jpg" },
      { filename: "chicago-2.jpg" },
      { filename: "chicago-3.jpg" },
      { filename: "chicago-4.jpg" },
      { filename: "chicago-5.jpg" },
      { filename: "chicago-7.jpg" },
      { filename: "chicago-8.jpg" },
      { filename: "chicago-9.jpg" },
    ],
  },
  {
    title: "Wildlife",
    slug: "wildlife",
    image: "/images/thumbs/other-2.jpg",
    date: "2024-01-01",
    featured: true,
    photos: [
      { filename: "other.jpg" },
      { filename: "other-2.jpg" },
      { filename: "other-4.jpg" },
      { filename: "other-5.jpg" },
      { filename: "other-7.jpg" },
      { filename: "other-8.jpg" },
      { filename: "other-9.jpg" },
      { filename: "other-10.jpg" },
    ],
  },
];

export const photoCollectionsBySlug = Object.fromEntries(
  photoCollections.map((collection) => [collection.slug, collection])
);
