import type { SiteConfig } from "@/content/types";

export const siteConfig: SiteConfig = {
  name: "Sohail Chutani",
  title: "Sohail Chutani",
  description:
    "Computer Engineering student building software, documenting places, and turning this portfolio into a home for both projects and photography.",
  email: "sohail@chutani.com",
  location: "Seattle, WA",
  tagline: "Computer Engineering student building software and chasing better light.",
  intro:
    "This site is evolving into a broader personal portfolio for engineering work, photography, and the systems behind both.",
  socialLinks: {
    github: "https://github.com/sohail-c",
    linkedin: "https://linkedin.com/in/sohailchutani",
  },
  featuredProjectSlugs: ["photo-portfolio"],
  featuredPhotoSlugs: ["senior-sendoff", "san-diego", "chicago-2024"],
  homeGalleryPhotos: [
    "chicago.jpg",
    "chicago-2.jpg",
    "chicago-3.jpg",
    "chicago-9.jpg",
    "chicago-5.jpg",
    "chicago-8.jpg",
    "chicago-4.jpg",
    "chicago-7.jpg",
    "oregon-2.jpg",
    "oregon-3.jpg",
    "oregon.jpg",
    "other.jpg",
    "other-2.jpg",
    "other-3.jpg",
    "other-4.jpg",
    "other-5.jpg",
    "other-6.jpg",
    "other-7.jpg",
    "other-8.jpg",
    "other-9.jpg",
    "other-10.jpg",
    "other-11.jpg",
    "road-trip.jpg",
    "road-trip-2.jpg",
    "san-diego.jpg",
    "san-diego-2.jpg",
    "san-diego-3.jpg",
    "san-diego-4.jpg",
    "san-diego-5.jpg",
    "san-diego-6.jpg",
    "san-diego-7.jpg",
    "san-diego-8.jpg",
    "san-diego-9.jpg",
    "san-diego-10.jpg",
  ],
};
